slam_toolbox:
  ros__parameters:
    publish_period_sec: 0.5
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "scanner/scan"
    map_update_rate_hz: 5.0
    max_duration_sec: 5.0
    use_map_topic: true
    use_static_map: false
  slam_toolbox_node:
    use_sim_time: false